version: "2"
networks:
  net1:
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
services:
  appdb:
    build: ./mysql
    container_name: "appdb"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /docker/mysql/conf:/etc/mysql/conf.d
      - /docker/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: 12312
    networks:
      net1:
        ipv4_address: 172.22.0.11  
  appredis:
    build: ./redis
    container_name: "appredis"
    restart: always
    command: [redis-server,/usr/local/etc/redis/redis.conf]
    ports:
      - 6379:6379
    volumes:
      - /docker/redis/redis.conf:/usr/local/etc/redis/redis.conf 
      - /docker/redis/data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      net1:
        ipv4_address: 172.22.0.10  
  appphp:
    build: ./php
    container_name: "appphp"
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /docker/nginx/www/:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
    networks:
      net1:
        ipv4_address: 172.22.0.12
    links:
      - "appdb"
      - "appredis"
  appnginx:
    build: ./nginx
    container_name: "appnginx"
    restart: always
    ports:
      - 80:80
    volumes:
      - /docker/nginx/www:/usr/share/nginx/html
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    networks:
      net1:
        ipv4_address: 172.22.0.13
    links:
      - "appphp"